"""Create messages table

Revision ID: 5f8a239f794a
Revises: f0d2612e2ce1
Create Date: 2025-11-20 15:10:24.625314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8a239f794a'
down_revision = 'f0d2612e2ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
