"""Create messages table

Revision ID: 900a58a858e8
Revises: 5f8a239f794a
Create Date: 2025-11-20 15:20:34.053157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900a58a858e8'
down_revision = '5f8a239f794a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
