"""Create messages table

Revision ID: f0d2612e2ce1
Revises: e7831b94d68e
Create Date: 2025-11-20 15:00:26.995845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d2612e2ce1'
down_revision = 'e7831b94d68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
